### ISSUE TITLE
Draw Lobby 

### ISSUE THREAD

**Issue by LastResortGames** [LastResortGames/Innkeeper#12]
As seen in the top area. With possibly little heroes being able to walk around in it. It should be about the size of two rooms next to each other. 

It needs to have a desk, some chairs, and a coffee table. Maybe a spot for the save point and bulliten board. The shop is the same as the main desk. (unless you think it'd be better elsewhere)

**Comment by f4ngy** [comment]
Added a base lobby image here https://github.com/LastResortGames/Innkeeper/blob/develop/assets/images/baseLobby.png

This is what it would look like with the save point and bulletin board in it http://i.imgur.com/iMHIG2l.png

Does this work alright?

**Comment by LastResortGames** [comment]
Make the bulletin board look likes its up on a wall somewhat. And add in door spaces to the walls for the hallways to rooms.

**Comment by f4ngy** [comment]
Closing since we decided the door spaces belong on the hallways rather than the lobby, and the bulletin board & save point will be overlayed programmatically rather than included in the image
