### ISSUE TITLE
Draw a bunch of types of rooms

### ISSUE THREAD

**Issue by f4ngy** [LastResortGames/Innkeeper#2]
Layer appropriately so pieces (i.e. beds, tables, etc) can be removed/added easily

**Comment by f4ngy** [comment]
I committed 4 different rooms for now. 1 bed room, 2 bed room, 3 bed room, and bonfire room. As well as a base empty room.

https://github.com/LastResortGames/Innkeeper/blob/develop/assets/images/oneBedRoom.png
https://github.com/LastResortGames/Innkeeper/blob/develop/assets/images/twoBedRoom.png
https://github.com/LastResortGames/Innkeeper/blob/develop/assets/images/threeBedRoom.png
https://github.com/LastResortGames/Innkeeper/blob/develop/assets/images/bonfireRoom.png
https://github.com/LastResortGames/Innkeeper/blob/develop/assets/images/roomBase.png

How many rooms do we want and did you want me to resize them and the lobby and commit them as the desired game size, or is that something we'll just do programmatically?

**Comment by LastResortGames** [comment]
Uhm we can resize them programatticly. I am not sure exactly what size they will need to be anyway atm. I like those rooms. Can you add a four bed room and add a Crafting spot to the 3 and 4.

**Comment by LastResortGames** [comment]
And Also can you just make a hallway with two doors across from each other.

**Comment by f4ngy** [comment]
Will do!

**Comment by f4ngy** [comment]
Revised third and fourth rooms

https://github.com/LastResortGames/Innkeeper/blob/develop/assets/images/threeBedRoom.png
https://github.com/LastResortGames/Innkeeper/blob/develop/assets/images/fourBedRoom.png

**Comment by f4ngy** [comment]
Closing for now unless we decided to add more types of rooms
