### ISSUE TITLE
Draw Desk as seen from Innkeeper position

### ISSUE THREAD

**Issue by LastResortGames** [LastResortGames/Innkeeper#4]
Draw a desk (like in Papers, Please) where you are looking at Heroes.

**Comment by f4ngy** [comment]
https://github.com/LastResortGames/Innkeeper/blob/develop/assets/images/desk.png

Does this work for what you're thinking?

**Comment by LastResortGames** [comment]
Pretty much. I was imagining it more at an angle a little like you are looking over it at the heroes.

**Comment by f4ngy** [comment]
Okay, I was trying to do what they did here http://i.playground.ru/i/19/64/60/00/screenshot/papers_please.jpg

This is what it looks like with a person behind it http://i.imgur.com/3XmkU8J.png

**Comment by LastResortGames** [comment]
Hmm. You're right. Yea it's fine like that.
